### PR TITLE
Bug/reconnection tile repetition

### LINKED ISSUE #332: Tiles are getting duplicated when disconnected and reconnect
Duplicate tiles coming up for existing participants when 
Network is disconnected and connected back

### PR DESCRIPTION
**Pull request by Decoder07**
Fixes:
- Tile Duplication on Reconnection

Closes #332

### CODE REVIEW

File: example/lib/meeting/meeting_page.dart [hunk 1]
```diff
@@ -231,24 +231,40 @@ class _MeetingPageState extends State<MeetingPage> with WidgetsBindingObserver {
         }
         setState(() {});
         break;
+      case 6:
```
Comment (jashan1498) [inline example/lib/meeting/meeting_page.dart:234]: remove these comments , lets try to keep example app cleaner

File: example/lib/meeting/meeting_store.dart [hunk 2]
```diff
@@ -94,8 +101,8 @@ abstract class MeetingStoreBase extends ChangeNotifier
   @action
   void startListen() {
     meetingController.addMeetingListener(this);
-    //startHMSLogger(HMSLogLevel.DEBUG, HMSLogLevel.DEBUG);
-    //addLogsListener();
+    // startHMSLogger(HMSLogLevel.VERBOSE, HMSLogLevel.VERBOSE);
```
Comment (jashan1498) [inline example/lib/meeting/meeting_store.dart:104]: remove

File: example/lib/meeting/meeting_page.dart (hunk 1 above)
Comment (Decoder07) [reply example/lib/meeting/meeting_page.dart:234]: Sure,this code was for active speaker mode so for now I have commented it.

**Review by Arunshaik2001 — APPROVED** [review]

**Review by ygit — APPROVED** [review]
